# output_dir: "output/pretrain-20221230-unet-textenc-coco-v1.5"
output_dir: "output/pretrain-20230117-finetune-cybertruck-2e-6-ocean"
logging_dir: "logs"

seed: 1337

# transform
image_size: 392
tgt_image_size: 512

model:
  train_text_encoder: True
  train_unet: True

  # stable diffusion and scheduler
  # pretrained_model_name_or_path: "CompVis/stable-diffusion-v1-4"
  pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
  # tune_num_layers_sd_text_encoder: 2
  revision: null

  # BLIP
  text_model: 'bert-base-uncased'

  pretrained: "/export/home/workspace/dreambooth/diffusers/BLIP2/pretrain_blipv2/checkpoint_14.pth"
  finetuned: '/export/home/workspace/dreambooth/diffusers/BLIP2/pretrain_blipv2/checkpoint_best.pth'


  vision_model: "clip"
  image_size: 392
  # tgt_image_size: 512
  # batch_size: 16

  num_query_token: 32
  max_text_length: 32
  embed_dim: 256

  num_proj_query_token: 32
  # num_proj_query_token: 4

  use_grad_checkpointing: True

# finetune specific
checkpoint: "/export/home/workspace/dreambooth/diffusers/output/pretrain-20230111-openimage/40000"
# image_dir: "/export/home/workspace/dreambooth/diffusers/data/alvan-nee"
image_dir: "/export/home/workspace/dreambooth/diffusers/data/cybertrucks"
subject: "truck"
force_init_annotations: False # if True, will always regenerate captions and bbox

# optimization
train_batch_size: 1
gradient_accumulation_steps: 1

learning_rate: 2e-6
lr_scheduler: constant
lr_warmup_steps: 0
scale_lr: False

adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-02
adam_epsilon: 1e-08

max_grad_norm: 20.0
mixed_precision: "no"  # ["no", "fp16", "bf16"] 

max_train_steps: 800
save_steps: 50
logging_steps: 20

# distribution
local_rank: -1