# output_dir: "output/pretrain-20221230-unet-textenc-coco-v1.5"
# output_dir: "output/finetune/202302250451-alvan-unet-textenc-2e-6"
# output_dir: "output/finetune/202302271238-df-bottle-1e-5"
# output_dir: "output/finetune/202302281028-df-bottle-1e-5-ckpt=200k-rr0-gpu8-1shot"
# output_dir: "output/finetune/202303011221-df-bottle-1e-5-ckpt=200k-rr0-gpu8-1shot"
output_dir: "output/finetune/202304040915-df-bottle-2e-6-ckpt=500k-rr0-gpu8-1shot"
logging_dir: "logs"

seed: 1337

# transform
image_size: 224
tgt_image_size: 512

model:
  train_text_encoder: False
  train_unet: False

  # stable diffusion and scheduler
  # pretrained_model_name_or_path: "CompVis/stable-diffusion-v1-4"
  pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
  # tune_num_layers_sd_text_encoder: 2
  revision: null

  # BLIP
  text_model: 'bert-base-uncased'

  pretrained: "/export/share/junnan-li/BLIP2/checkpoint/clip_q16.pth"

  vision_model: "clip"
  image_size: 224
  # tgt_image_size: 512
  # batch_size: 16

  num_query_token: 16
  max_text_length: 32
  embed_dim: 256

  # num_proj_query_token: 32
  # num_proj_query_token: 4

  use_grad_checkpointing: True

# finetune specific
# checkpoint: "/export/home/workspace/dreambooth/diffusers/output/pretrain-20230111-openimage/35000"
# checkpoint: "/export/home/workspace/dreambooth/diffusers/output/pretrain-20230222-unet-textenc-v1.5-capfilt6b7-fullmask-synbbox-rr0.33/100000"
# checkpoint: "/export/home/workspace/dreambooth/diffusers/output/pretrain-20230225-unet-textenc-v1.5-capfilt6b7-fullmask-synbbox-rr0/200000"
# checkpoint: ""
checkpoint: "/export/home/workspace/dreambooth/diffusers/output/pretrain-202302315-unet-textenc-v1.5-capfilt6b7-synbbox-matting-rr0-drop15-500k/500000"
# checkpoint: "/export/home/workspace/dreambooth/diffusers/output/pretrain-20230225-unet-textenc-v1.5-capfilt6b7-fullmask-synbbox-rr0/100000"
# image_dir: "/export/home/workspace/dreambooth/diffusers/data/df-bottle-synthetic/"
image_dir: "/export/home/workspace/dreambooth/diffusers/data/df-bottle"
subject: "bottle"
force_init_annotations: False # if True, will always regenerate captions and bbox

# optimization
train_batch_size: 2
gradient_accumulation_steps: 1

learning_rate: 2e-6
lr_scheduler: constant
lr_warmup_steps: 0
scale_lr: False

adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-02
adam_epsilon: 1e-08

max_grad_norm: 20.0
mixed_precision: "no"  # ["no", "fp16", "bf16"] 

max_train_steps: 50
save_steps: 5
logging_steps: 5

# distribution
local_rank: -1

val_subject: "bottle"
val_image_path: "/export/home/workspace/dreambooth/diffusers/data/df-bottle/df-bottle.jpg"
# val_image_path: "/export/home/workspace/dreambooth/diffusers/data/df-bottle/df-bottle_syn.jpg"
val_prompts:
  - "at the grand canyon"
  - "buried in sands"
  - "in the ocean"
  - "two of them"
  - "as lamp"
  - "by window"
  - "in snowy forest"
  # - "in the city of versailles"
  # - "wet in water"
  # - "with the night sky"

save_model: False